@extends('layouts.admin')
@section('title','Quản lý trang — Kaiyo Admin')
@section('content')
<section class="mx-auto max-w-[1440px] px-5 py-10 lg:px-8">
    <p class="text-sm font-semibold uppercase tracking-widest text-brand">Content</p>
    <h1 class="mt-2 text-3xl font-bold">Trang nội dung</h1>
    <p class="mt-2 text-ink-muted">Bản nháp và bản đã xuất bản có quyền riêng biệt. Nội dung công khai luôn được render từ revision đã xuất bản.</p>
    @if(session('status'))<x-ui.alert class="mt-6" tone="success">{{ session('status') }}</x-ui.alert>@endif
    @if($errors->any())<x-ui.alert class="mt-6" tone="danger">{{ $errors->first() }}</x-ui.alert>@endif

    <div class="mt-8 grid gap-6 xl:grid-cols-[minmax(0,1fr)_24rem]">
        <div>
            <x-ui.card title="Tìm và lọc">
                <form method="GET" action="{{ route('admin.pages') }}" class="grid gap-4 md:grid-cols-[1fr_14rem_auto] md:items-end">
                    <x-ui.input name="q" label="Slug hoặc tiêu đề" :value="$directory->query" />
                    <div><label for="page-status" class="block text-sm font-medium">Trạng thái</label><select id="page-status" name="status" class="mt-2 min-h-11 w-full rounded-control border border-line bg-surface px-3 py-2"><option value="">Tất cả</option>@foreach(['draft'=>'Nháp','published'=>'Đã xuất bản','unpublished'=>'Đã gỡ'] as $value=>$label)<option value="{{ $value }}" @selected($directory->status===$value)>{{ $label }}</option>@endforeach</select></div>
                    <x-ui.button type="submit" icon="funnel">Áp dụng</x-ui.button>
                </form>
            </x-ui.card>
            <div class="mt-6 space-y-3">
                @forelse($directory->pages as $page)
                    <article class="rounded-control border border-line bg-surface p-5">
                        <div class="flex flex-wrap items-start justify-between gap-4"><div><h2 class="font-semibold">{{ $page['title'] }}</h2><p class="mt-1 font-mono text-sm text-ink-muted">/noi-dung/{{ $page['slug'] }}</p></div><div class="flex gap-2"><span class="rounded-full bg-canvas px-3 py-1 text-xs font-semibold uppercase">{{ $page['status'] }}</span>@if($page['has_published_revision'])<span class="rounded-full bg-success-soft px-3 py-1 text-xs font-semibold text-on-success">LIVE</span>@endif</div></div>
                        <p class="mt-3 text-sm text-ink-muted">Revision {{ $page['revision_no'] }} · version {{ $page['lock_version'] }} · cập nhật {{ $page['updated_at'] }}</p>
                        <div class="mt-4 flex flex-wrap gap-2">@if($page['has_published_revision'])<x-ui.button :href="route('public.page',$page['slug'])" variant="secondary" size="sm">Xem trang</x-ui.button>@endif @if($adminNavigation['content_publish'] ?? false) @if($page['has_published_revision'])<form method="POST" action="{{ route('admin.pages.unpublish',$page['public_id']) }}">@csrf<input type="hidden" name="lock_version" value="{{ $page['lock_version'] }}"><x-ui.button type="submit" variant="danger" size="sm">Gỡ xuất bản</x-ui.button></form>@endif @if($page['status']!=='published')<form method="POST" action="{{ route('admin.pages.publish',$page['public_id']) }}">@csrf<input type="hidden" name="lock_version" value="{{ $page['lock_version'] }}"><x-ui.button type="submit" size="sm">Xuất bản revision {{ $page['revision_no'] }}</x-ui.button></form>@endif @endif</div>
                        <details class="mt-4"><summary class="cursor-pointer text-sm font-semibold text-brand">Tạo revision thay thế</summary><form method="POST" action="{{ route('admin.pages.revise',$page['public_id']) }}" class="mt-4 grid gap-3">@csrf<input type="hidden" name="lock_version" value="{{ $page['lock_version'] }}"><x-ui.input name="title" label="Tiêu đề revision mới" required /><x-ui.input name="summary" label="Tóm tắt revision mới" /><div><label class="block text-sm font-medium" for="body-{{ $page['public_id'] }}">Nội dung Markdown</label><textarea id="body-{{ $page['public_id'] }}" name="body_markdown" rows="8" required class="mt-2 w-full rounded-control border border-line bg-surface px-3 py-2"></textarea></div><x-ui.button type="submit" variant="secondary" size="sm">Lưu revision mới</x-ui.button></form></details>
                        <details class="mt-4"><summary class="cursor-pointer text-sm font-semibold text-brand">Media của revision</summary><div class="mt-3 space-y-2">@foreach($page['media'] as $reference)<div class="flex items-center justify-between gap-2"><span>{{ $reference['original_name'] }} · {{ $reference['purpose'] }}</span><form method="POST" action="{{ route('admin.pages.media.detach',['page'=>$page['public_id'],'asset'=>$reference['public_id'],'purpose'=>$reference['purpose']]) }}">@csrf @method('DELETE')<input type="hidden" name="lock_version" value="{{ $page['lock_version'] }}"><x-ui.button type="submit" variant="secondary" size="sm">Gỡ</x-ui.button></form></div>@endforeach</div><form method="POST" action="{{ route('admin.pages.media.attach',$page['public_id']) }}" class="mt-3 grid gap-2 md:grid-cols-3">@csrf<input type="hidden" name="lock_version" value="{{ $page['lock_version'] }}"><x-ui.input name="asset_public_id" label="Media public ID" required /><x-ui.input name="purpose" label="Purpose" required /><x-ui.input name="sort_order" type="number" label="Thứ tự" value="0" required /><div class="md:col-span-3"><x-ui.button type="submit" variant="secondary" size="sm">Gắn media</x-ui.button></div></form></details>
                        @if($adminNavigation['content_publish'] ?? false)<details class="mt-4"><summary class="cursor-pointer text-sm font-semibold text-brand">Lên lịch publish/unpublish</summary><form method="POST" action="{{ route('admin.pages.schedule',$page['public_id']) }}" class="mt-4 grid gap-3 md:grid-cols-2">@csrf<input type="hidden" name="lock_version" value="{{ $page['lock_version'] }}"><input type="hidden" name="operation_key" value="cms.page.{{ $page['public_id'] }}.{{ \Illuminate\Support\Str::uuid() }}"><div><label class="block text-sm font-medium" for="schedule-action-{{ $page['public_id'] }}">Hành động</label><select id="schedule-action-{{ $page['public_id'] }}" name="action" class="mt-2 min-h-11 w-full rounded-control border border-line bg-surface px-3 py-2"><option value="publish">Publish revision hiện tại</option><option value="unpublish">Unpublish</option></select></div><x-ui.input type="datetime-local" name="due_at" label="Thời điểm chạy" required /><div class="md:col-span-2"><x-ui.button type="submit" variant="secondary" size="sm">Lưu lịch</x-ui.button></div></form></details>@endif
                    </article>
                @empty
                    <x-ui.empty-state title="Chưa có trang nội dung" description="Tạo bản nháp đầu tiên bằng biểu mẫu bên cạnh." />
                @endforelse
            </div>
            @if($directory->previousCursor || $directory->nextCursor)<nav class="mt-6 flex justify-between">@if($directory->previousCursor)<x-ui.button :href="route('admin.pages',array_filter(['q'=>$directory->query,'status'=>$directory->status,'cursor'=>$directory->previousCursor]))" variant="secondary">Trang trước</x-ui.button>@else<span></span>@endif @if($directory->nextCursor)<x-ui.button :href="route('admin.pages',array_filter(['q'=>$directory->query,'status'=>$directory->status,'cursor'=>$directory->nextCursor]))" variant="secondary">Trang sau</x-ui.button>@endif</nav>@endif
        </div>
        <x-ui.card title="Tạo bản nháp"><form method="POST" action="{{ route('admin.pages.store') }}" class="space-y-4">@csrf<x-ui.input name="title" label="Tiêu đề" :value="old('title')" required /><x-ui.input name="slug" label="Slug" :value="old('slug')" required /><x-ui.input name="summary" label="Tóm tắt" :value="old('summary')" /><div><label for="body-markdown" class="block text-sm font-medium">Nội dung Markdown</label><textarea id="body-markdown" name="body_markdown" rows="12" required class="mt-2 w-full rounded-control border border-line bg-surface px-3 py-2">{{ old('body_markdown') }}</textarea></div><x-ui.button type="submit" icon="document-plus">Lưu bản nháp</x-ui.button></form></x-ui.card>
    </div>
</section>
@endsection
