@extends('layouts.staff')

@section('title', $title.' — Kaiyo Sales')

@section('content')
<section class="mx-auto max-w-[1440px] px-5 py-10 lg:px-8">
    <p class="text-sm font-semibold uppercase tracking-widest text-brand">Sales</p><h1 class="mt-2 text-3xl font-bold">{{ $title }}</h1><p class="mt-2 text-ink-muted">Dữ liệu đọc theo entitlement; thao tác thay đổi trạng thái vẫn thuộc domain workflow riêng.</p>
    <x-ui.card class="mt-8" title="Tìm và lọc"><form method="GET" action="{{ route($routeName) }}" class="grid gap-4 md:grid-cols-[1fr_14rem_auto] md:items-end"><x-ui.input name="q" label="Public ID hoặc tên khách hàng" :value="$directory->query" /><div><label for="commercial-status" class="block text-sm font-medium">Trạng thái</label><select id="commercial-status" name="status" class="mt-2 min-h-11 w-full rounded-control border border-line bg-surface px-3 py-2"><option value="">Tất cả</option>@foreach($states as $state)<option value="{{ $state }}" @selected($directory->status===$state)>{{ $state }}</option>@endforeach</select></div><x-ui.button type="submit">Áp dụng</x-ui.button></form></x-ui.card>
    <div class="mt-6 overflow-hidden rounded-panel border border-line bg-surface"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-line text-left text-sm"><thead class="bg-surface-muted"><tr><th class="px-5 py-3">Public ID</th><th class="px-5 py-3">Khách hàng</th><th class="px-5 py-3">Trạng thái</th><th class="px-5 py-3">Giá trị</th><th class="px-5 py-3">Chi tiết</th></tr></thead><tbody class="divide-y divide-line">@forelse($directory->records as $record)<tr><td class="px-5 py-4 font-mono text-xs">{{ $record['public_id'] }}</td><td class="px-5 py-4 font-semibold">{{ $record['party'] }}</td><td class="px-5 py-4"><x-ui.badge>{{ $record['state'] }}</x-ui.badge></td><td class="px-5 py-4 font-semibold">{{ number_format($record['amount'],0,',','.') }} {{ $record['currency'] }}</td><td class="px-5 py-4 text-ink-muted">{{ $record['detail'] }}</td></tr>@empty<tr><td colspan="5" class="px-5 py-10"><x-ui.empty-state :title="'Chưa có '.$title" description="Không có bản ghi phù hợp trong phạm vi được phép." /></td></tr>@endforelse</tbody></table></div></div>
    @if($directory->previousCursor || $directory->nextCursor)<nav class="mt-6 flex justify-between" aria-label="Phân trang">@if($directory->previousCursor)<x-ui.button :href="route($routeName,array_filter(['q'=>$directory->query,'status'=>$directory->status,'cursor'=>$directory->previousCursor]))" variant="secondary">Trang trước</x-ui.button>@else<span></span>@endif @if($directory->nextCursor)<x-ui.button :href="route($routeName,array_filter(['q'=>$directory->query,'status'=>$directory->status,'cursor'=>$directory->nextCursor]))" variant="secondary">Trang sau</x-ui.button>@endif</nav>@endif
</section>
@endsection
