@extends('layouts.staff')

@section('title', 'Công ty — Kaiyo Sales')

@section('content')
<section class="mx-auto max-w-[1440px] px-5 py-10 lg:px-8">
    <div class="flex flex-wrap items-end justify-between gap-5"><div><p class="text-sm font-semibold uppercase tracking-widest text-brand">CRM</p><h1 class="mt-2 text-3xl font-bold">Công ty</h1><p class="mt-2 text-ink-muted">Hồ sơ pháp nhân và khách hàng doanh nghiệp.</p></div><dl class="flex gap-3 text-sm">@foreach($directory->statusCounts as $state=>$count)<div class="min-w-24 rounded-control border border-line bg-surface px-4 py-3"><dt class="text-ink-muted">{{ $state }}</dt><dd class="mt-1 text-xl font-bold">{{ number_format($count) }}</dd></div>@endforeach</dl></div>
    @if(session('status'))<x-ui.alert class="mt-6" tone="success" title="Đã cập nhật">{{ session('status') }}</x-ui.alert>@endif
    @if($errors->any())<x-ui.alert class="mt-6" tone="danger" title="Không thể hoàn tất"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></x-ui.alert>@endif
    @if($staffNavigation['can_create_companies'] ?? false)<x-ui.card class="mt-8" title="Tạo công ty" description="Mã số thuế được lưu nhưng không đánh dấu xác minh nếu chưa có bằng chứng."><form method="POST" action="{{ route('sales.companies.store') }}" class="grid gap-4 md:grid-cols-2">@csrf<x-ui.input name="legal_name" label="Tên pháp lý" required /><x-ui.input name="display_name" label="Tên hiển thị" /><x-ui.input name="tax_code" label="Mã số thuế" /><x-ui.input name="source" label="Nguồn" /><div class="md:col-span-2"><x-ui.button type="submit">Tạo công ty</x-ui.button></div></form></x-ui.card>@endif
    <x-ui.card class="mt-6" title="Tìm và lọc"><form method="GET" action="{{ route('sales.companies') }}" class="grid gap-4 md:grid-cols-[1fr_14rem_auto] md:items-end"><x-ui.input name="q" label="Tên hoặc mã số thuế" :value="$directory->query" /><div><label for="company-status" class="block text-sm font-medium">Trạng thái</label><select id="company-status" name="status" class="mt-2 min-h-11 w-full rounded-control border border-line bg-surface px-3 py-2"><option value="">Tất cả</option>@foreach(['active','inactive'] as $state)<option value="{{ $state }}" @selected($directory->status===$state)>{{ $state }}</option>@endforeach</select></div><x-ui.button type="submit">Áp dụng</x-ui.button></form></x-ui.card>
    <div class="mt-6 overflow-hidden rounded-panel border border-line bg-surface"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-line text-left text-sm"><thead class="bg-surface-muted"><tr><th class="px-5 py-3">Công ty</th><th class="px-5 py-3">Tên pháp lý</th><th class="px-5 py-3">Mã số thuế</th><th class="px-5 py-3">Trạng thái</th></tr></thead><tbody class="divide-y divide-line">@forelse($directory->companies as $company)<tr><td class="px-5 py-4"><a href="{{ route('sales.companies.show', $company['public_id']) }}" class="font-semibold text-brand hover:underline">{{ $company['display_name'] }}</a></td><td class="px-5 py-4">{{ $company['legal_name'] }}</td><td class="px-5 py-4">{{ $company['tax_code'] ?? 'Chưa có' }}</td><td class="px-5 py-4"><x-ui.badge :tone="$company['status']==='active'?'success':'neutral'">{{ $company['status'] }}</x-ui.badge></td></tr>@empty<tr><td colspan="4" class="px-5 py-10"><x-ui.empty-state title="Không tìm thấy công ty" description="Thử đổi bộ lọc hoặc tạo hồ sơ mới nếu có quyền." /></td></tr>@endforelse</tbody></table></div></div>
    @if($directory->previousCursor || $directory->nextCursor)<nav class="mt-6 flex justify-between" aria-label="Phân trang công ty">@if($directory->previousCursor)<x-ui.button :href="route('sales.companies',array_filter(['q'=>$directory->query,'status'=>$directory->status,'cursor'=>$directory->previousCursor]))" variant="secondary">Trang trước</x-ui.button>@else<span></span>@endif @if($directory->nextCursor)<x-ui.button :href="route('sales.companies',array_filter(['q'=>$directory->query,'status'=>$directory->status,'cursor'=>$directory->nextCursor]))" variant="secondary">Trang sau</x-ui.button>@endif</nav>@endif
</section>
@endsection
