@extends('layouts.staff')

@section('title', $company->displayName.' — Kaiyo Sales')

@section('content')
<section class="mx-auto max-w-5xl px-5 py-10 lg:px-8">
    <a href="{{ route('sales.companies') }}" class="inline-flex items-center gap-2 text-sm font-semibold text-brand hover:underline"><x-heroicon-o-arrow-left class="size-4" aria-hidden="true" />Danh sách công ty</a>
    <div class="mt-5 flex flex-wrap justify-between gap-4"><div><p class="text-sm font-semibold uppercase tracking-widest text-brand">Company 360</p><h1 class="mt-2 text-3xl font-bold">{{ $company->displayName }}</h1><p class="mt-2 text-ink-muted">{{ $company->legalName }}</p><p class="mt-1 font-mono text-xs text-ink-muted">{{ $company->publicId }}</p></div><x-ui.badge :tone="$company->status==='active'?'success':'neutral'">{{ $company->status }}</x-ui.badge></div>
    @if(session('status'))<x-ui.alert class="mt-6" tone="success" title="Đã cập nhật">{{ session('status') }}</x-ui.alert>@endif
    @if($errors->any())<x-ui.alert class="mt-6" tone="danger" title="Không thể hoàn tất"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></x-ui.alert>@endif
    <x-ui.card class="staff-reveal staff-reveal-delay-1 mt-8" title="Hồ sơ"><dl class="grid gap-4 text-sm sm:grid-cols-2"><div><dt class="text-ink-muted">Mã số thuế</dt><dd class="mt-1 font-medium">{{ $company->taxCode ?? 'Chưa có' }}</dd></div><div><dt class="text-ink-muted">Phiên bản</dt><dd class="mt-1 font-medium">{{ $company->version }}</dd></div></dl></x-ui.card>
    @if($company->canManageMembers)<x-ui.card class="staff-reveal staff-reveal-delay-2 mt-6" title="Thêm thành viên" description="Membership không tự cấp quyền. Chỉ các capability bạn đang được ủy quyền mới xuất hiện bên dưới."><form method="POST" action="{{ route('sales.companies.members.store', $company->publicId) }}" class="space-y-5">@csrf<x-ui.input name="member_public_id" label="Public ID tài khoản" required minlength="26" maxlength="26" />@if($company->delegableCapabilities !== [])<fieldset><legend class="text-sm font-semibold text-ink">Capability cấp cùng membership</legend><p class="mt-1 text-sm text-ink-muted">Có thể bỏ trống để chỉ thêm membership.</p><div class="mt-3 grid gap-2 sm:grid-cols-2">@foreach($company->delegableCapabilities as $capability)<label class="flex min-h-11 items-center gap-3 rounded-control border border-line bg-surface-muted px-3 py-2 text-sm text-ink"><input class="size-4 rounded border-line text-brand focus:ring-focus" type="checkbox" name="capabilities[]" value="{{ $capability['code'] }}" @checked(in_array($capability['code'], old('capabilities', []), true)) /><span><span class="block font-medium">{{ $capability['code'] }}</span><span class="block text-xs text-ink-muted">Module {{ $capability['module'] }}</span></span></label>@endforeach</div></fieldset>@else<p class="rounded-control border border-line bg-surface-muted p-3 text-sm text-ink-muted">Bạn chưa có capability nào có thể ủy quyền trực tiếp.</p>@endif<x-ui.button type="submit">Thêm thành viên</x-ui.button></form></x-ui.card>@endif
    <x-ui.card class="staff-reveal staff-reveal-delay-3 mt-6" title="Thành viên"><div class="space-y-3">@forelse($company->members as $member)<article class="rounded-control border border-line bg-surface-muted p-4 text-sm"><div class="flex flex-wrap justify-between gap-3"><span><strong>{{ $member['email'] }}</strong><small class="mt-1 block font-mono text-ink-muted">{{ $member['account_public_id'] }}</small></span><x-ui.badge :tone="$member['status']==='active'?'success':'neutral'">{{ $member['status'] }}</x-ui.badge></div><p class="mt-2 text-ink-muted">Bắt đầu {{ $member['starts_at'] }}@if($member['ends_at']) · kết thúc {{ $member['ends_at'] }}@endif</p><div class="mt-3 border-t border-line pt-3"><p class="text-xs font-semibold uppercase tracking-wide text-ink-muted">Capability đang hiệu lực</p>@if($member['capabilities'] !== [])<ul class="mt-2 flex flex-wrap gap-2">@foreach($member['capabilities'] as $capability)<li class="inline-flex items-center gap-2 rounded-control border border-line bg-surface px-2 py-1 font-mono text-xs text-ink"><span>{{ $capability }}</span>@if($company->canManageMembers)<form method="POST" action="{{ route('sales.companies.members.capabilities.destroy', ['company' => $company->publicId, 'member' => $member['account_public_id'], 'capability' => $capability]) }}">@csrf @method('DELETE')<button type="submit" class="inline-flex min-h-7 items-center text-danger hover:underline" aria-label="Thu hồi capability {{ $capability }}">Thu hồi</button></form>@endif</li>@endforeach</ul>@else<p class="mt-2 text-sm text-ink-muted">Chưa có capability nào được cấp.</p>@endif</div></article>@empty<x-ui.empty-state title="Chưa có thành viên" description="Membership được quản lý riêng với capability." />@endforelse</div></x-ui.card>
</section>
@endsection
